
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const COLLAPSE = 'COLLAPSE';

export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';

export const GET_VILLAGE_SUCCESS = 'GET_VILLAGE_SUCCESS';

export const PEOPLE_FORM_ADD = 'PEOPLE_FORM_ADD';

export const PEOPLE_FORM_EDIT = 'PEOPLE_FORM_EDIT';

export const UPDATE_PEOPLE_SEARCH_STATE = 'UPDATE_PEOPLE_SEARCH_STATE';

export const RESET_PEOPLE_SEARCH_STATE = 'RESET_PEOPLE_SEARCH_STATE';