export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const COLLAPSE = 'COLLAPSE';

export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';

export const GET_VILLAGE_SUCCESS = 'GET_VILLAGE_SUCCESS';

export const PEOPLE_FORM_ADD = 'PEOPLE_FORM_ADD';

export const PEOPLE_FORM_EDIT = 'PEOPLE_FORM_EDIT';

export const UPDATE_PEOPLE_SEARCH_STATE = 'UPDATE_PEOPLE_SEARCH_STATE';

export const RESET_PEOPLE_SEARCH_STATE = 'RESET_PEOPLE_SEARCH_STATE';

export const PASSWORD_MODAL_SHOW = 'PASSWORD_MODAL_SHOW';

export const PASSWORD_MODAL_HIDE = 'PASSWORD_MODAL_HIDE';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';

export const PRODUCT_MODAL = 'PRODUCT_MODAL';

// 产品入库

export const GET_ENROLL_SUCCESS = 'GET_ENROLL_SUCCESS';

export const GET_PEOPLE_FOR_ENROLL_SUCCESS = 'GET_PEOPLE_FOR_ENROLL_SUCCESS';

export const ENROLL_MODAL = 'ENROLL_MODAL';

// 打印机列表

export const GET_PRINTER_LIST_SUCCESS = 'GET_PRINTER_LIST_SUCCESS';

// 打印预览
export const PRINT_PREVIEW_MODAL = 'PRINT_PREVIEW_MODAL'; 

// 产品入库的初始化渲染
export const GET_ENROLL_RESET = 'GET_ENROLL_RESET';
export const GET_PEOPLE_RESET = 'GET_PEOPLE_RESET'; 
export const GET_PRODUCT_RESET = 'GET_PRODUCT_RESET';