export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const COLLAPSE = 'COLLAPSE';

export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';

export const GET_VILLAGE_SUCCESS = 'GET_VILLAGE_SUCCESS';

export const PEOPLE_FORM_ADD = 'PEOPLE_FORM_ADD';

export const PEOPLE_FORM_EDIT = 'PEOPLE_FORM_EDIT';

export const UPDATE_PEOPLE_SEARCH_STATE = 'UPDATE_PEOPLE_SEARCH_STATE';

export const RESET_PEOPLE_SEARCH_STATE = 'RESET_PEOPLE_SEARCH_STATE';

export const PASSWORD_MODAL_SHOW = 'PASSWORD_MODAL_SHOW';

export const PASSWORD_MODAL_HIDE = 'PASSWORD_MODAL_HIDE';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';

export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'; 

export const PRODUCT_MODAL = 'PRODUCT_MODAL';

// 产品入库

export const GET_ENROLL_SUCCESS = 'GET_ENROLL_SUCCESS';

